/***************************************************************
 Hospital ERP - SQL Server Schema & Core Stored Procedures
 Normalized design, identities, indexes, constraints, transactions
 Author: Generated by Mugisha Micheal 
 Date: 2025-09-02
***************************************************************/

SET NOCOUNT ON;
GO

-- Use / create database (optional)
IF DB_ID('HospitalERP') IS NULL
BEGIN
    CREATE DATABASE HospitalERP;
END
GO
USE HospitalERP;
GO

/***************************************************************
1) Lookup tables (normalized)
***************************************************************/

-- Roles
CREATE TABLE dbo.Roles (
    RoleId INT IDENTITY(1,1) PRIMARY KEY,
    RoleName NVARCHAR(50) NOT NULL UNIQUE,
    Description NVARCHAR(250) NULL
);

-- User status
CREATE TABLE dbo.UserStatus (
    UserStatusId TINYINT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO dbo.UserStatus(UserStatusId, Name) VALUES
(1,'Active'),(2,'Inactive'),(3,'Suspended');





-- Service catalog (billable items)
CREATE TABLE dbo.ServiceCategories (
    CategoryId INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE dbo.Services (
    ServiceId INT IDENTITY(1,1) PRIMARY KEY,
    CategoryId INT NOT NULL FOREIGN KEY REFERENCES dbo.ServiceCategories(CategoryId),
    Code NVARCHAR(30) NOT NULL UNIQUE,
    Name NVARCHAR(200) NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL CHECK (UnitPrice >= 0),
    IsBillable BIT NOT NULL DEFAULT 1,
    CONSTRAINT UX_Services_Code_Name UNIQUE(Code, Name)
);

-- Appointment types
CREATE TABLE dbo.AppointmentTypes (
    AppointmentTypeId TINYINT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO dbo.AppointmentTypes VALUES (1,'InPerson'),(2,'Online'),(3,'Phone');

-- Triage severity
CREATE TABLE dbo.TriageSeverity (
    SeverityId TINYINT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE,
    Priority INT NOT NULL
);
INSERT INTO dbo.TriageSeverity VALUES (1,'Critical',1),(2,'Urgent',2),(3,'Non-Urgent',3);

-- Payment methods
CREATE TABLE dbo.PaymentMethods (
    PaymentMethodId TINYINT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO dbo.PaymentMethods VALUES (1,'Cash'),(2,'Card'),(3,'MobileMoney'),(4,'Insurance');

-- Ambulance status
CREATE TABLE dbo.AmbulanceStatus (
    AmbulanceStatusId TINYINT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO dbo.AmbulanceStatus VALUES (1,'Available'),(2,'Dispatched'),(3,'InService'),(4,'Maintenance');

-- Lab test catalog
CREATE TABLE dbo.LabTests (
    LabTestId INT IDENTITY(1,1) PRIMARY KEY,
    Code NVARCHAR(50) NOT NULL UNIQUE,
    Name NVARCHAR(200) NOT NULL,
    Category NVARCHAR(100),
    Price DECIMAL(18,2) NOT NULL CHECK (Price >= 0)
);

-- Drug catalog
CREATE TABLE dbo.Drugs (
    DrugId INT IDENTITY(1,1) PRIMARY KEY,
    GenericName NVARCHAR(200) NOT NULL,
    BrandName NVARCHAR(200),
    Form NVARCHAR(50), -- tablet, syrup
    Strength NVARCHAR(50),
    Unit NVARCHAR(20),
    UNIQUE(GenericName, BrandName, Strength)
);

-- Ward types
CREATE TABLE dbo.WardTypes (
    WardTypeId TINYINT PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE
);
INSERT INTO dbo.WardTypes VALUES (1,'General'),(2,'ICU'),(3,'OT'),(4,'Maternity');

-- Nursing observation types
CREATE TABLE dbo.ObservationTypes (
    ObservationTypeId INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    Unit NVARCHAR(50)
);

/***************************************************************
2) Core user and identity model
Normalized: single Users table, Roles in mapping
***************************************************************/

CREATE TABLE dbo.Users (
    UserId INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(150) NULL, -- for staff login; not required for patients
    Email NVARCHAR(255) NULL,
    Phone NVARCHAR(30) NULL,
    PasswordHash NVARCHAR(512) NULL, -- use appropriate hashing in app
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    DateOfBirth DATE NULL,
    Gender CHAR(1) NULL CHECK (Gender IN ('M','F')),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CreatedBy INT NULL REFERENCES dbo.Users(UserId),
    StatusId TINYINT NOT NULL DEFAULT 1 REFERENCES dbo.UserStatus(UserStatusId),
    CONSTRAINT UX_Users_Email UNIQUE (Email),
    CONSTRAINT UX_Users_Phone UNIQUE (Phone)
);
-- Indexes to speed lookups
CREATE INDEX IX_Users_Email ON dbo.Users(Email);
CREATE INDEX IX_Users_Phone ON dbo.Users(Phone);
CREATE INDEX IX_Users_Name ON dbo.Users(LastName, FirstName);

/* UserRoles mapping for RBAC */
CREATE TABLE dbo.UserRoles (
    UserRoleId INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId) ON DELETE CASCADE,
    RoleId INT NOT NULL FOREIGN KEY REFERENCES dbo.Roles(RoleId),
    AssignedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UNIQUE (UserId, RoleId)
);

/***************************************************************
3) Patients & Demographics (normalized)
***************************************************************/

CREATE TABLE dbo.Patients (
    PatientId INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NULL UNIQUE FOREIGN KEY REFERENCES dbo.Users(UserId), -- optional linkage for patients with user accounts
    MedicalRecordNumber NVARCHAR(50) NOT NULL UNIQUE, -- MRN
    NationalId NVARCHAR(50) NULL,
    EmergencyContactName NVARCHAR(200) NULL,
    EmergencyContactPhone NVARCHAR(30) NULL,
    PrimaryInsurerId INT NULL, -- FK to InsurancePolicies added later
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE INDEX IX_Patients_MRN ON dbo.Patients(MedicalRecordNumber);

/***************************************************************
4) Visits (Encounters) - central clinical interaction table
Normalized: link to patient, admitting doctor, visit type, etc.
***************************************************************/

CREATE TABLE dbo.VisitTypes (
    VisitTypeId TINYINT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO dbo.VisitTypes VALUES (1,'Consultation'),(2,'Emergency'),(3,'FollowUp'),(4,'Admission');

CREATE TABLE dbo.Visits (
    VisitId BIGINT IDENTITY(1,1) PRIMARY KEY,
    PatientId INT NOT NULL FOREIGN KEY REFERENCES dbo.Patients(PatientId),
    VisitTypeId TINYINT NOT NULL FOREIGN KEY REFERENCES dbo.VisitTypes(VisitTypeId),
    RegisteredByUserId INT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    RegisteredAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ChiefComplaint NVARCHAR(1000) NULL,
    VisitStatus NVARCHAR(50) NOT NULL DEFAULT 'Open', -- consider lookup
    VisitStart DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    VisitEnd DATETIME2 NULL,
    CONSTRAINT IDX_Visits_Patient_RegisteredAt NONCLUSTERED (PatientId, RegisteredAt)
);

/***************************************************************
5) Appointments
***************************************************************/

CREATE TABLE dbo.Appointments (
    AppointmentId BIGINT IDENTITY(1,1) PRIMARY KEY,
    PatientId INT NOT NULL FOREIGN KEY REFERENCES dbo.Patients(PatientId),
    RequestedByUserId INT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    AppointmentTypeId TINYINT NOT NULL FOREIGN KEY REFERENCES dbo.AppointmentTypes(AppointmentTypeId),
    ScheduledAt DATETIME2 NOT NULL,
    DurationMinutes INT NOT NULL DEFAULT 30 CHECK (DurationMinutes > 0),
    ProviderUserId INT NULL FOREIGN KEY REFERENCES dbo.Users(UserId), -- doctor
    Status NVARCHAR(50) NOT NULL DEFAULT 'Scheduled',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE INDEX IX_Appointments_ScheduledAt ON dbo.Appointments(ScheduledAt);
CREATE INDEX IX_Appointments_Patient ON dbo.Appointments(PatientId);

/***************************************************************
6) Triage records (per visit)
***************************************************************/

CREATE TABLE dbo.TriageRecords (
    TriageId BIGINT IDENTITY(1,1) PRIMARY KEY,
    VisitId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Visits(VisitId) ON DELETE CASCADE,
    RecordedByUserId INT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    RecordedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    SeverityId TINYINT NOT NULL FOREIGN KEY REFERENCES dbo.TriageSeverity(SeverityId),
    Vitals NVARCHAR(1000) NULL, -- JSON or structured in separate table if required
    Notes NVARCHAR(2000) NULL
);
CREATE INDEX IX_Triage_Visit_Severity ON dbo.TriageRecords(VisitId, SeverityId);

/***************************************************************
7) Doctor notes, referrals, prescriptions
***************************************************************/

CREATE TABLE dbo.DoctorNotes (
    NoteId BIGINT IDENTITY(1,1) PRIMARY KEY,
    VisitId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Visits(VisitId) ON DELETE CASCADE,
    AuthorUserId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    NoteType NVARCHAR(50) NOT NULL DEFAULT 'General',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Content NVARCHAR(MAX) NOT NULL
);
CREATE INDEX IX_DoctorNotes_Visit ON dbo.DoctorNotes(VisitId);

CREATE TABLE dbo.Referrals (
    ReferralId BIGINT IDENTITY(1,1) PRIMARY KEY,
    FromUserId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    ToUserId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    VisitId BIGINT NULL FOREIGN KEY REFERENCES dbo.Visits(VisitId),
    Reason NVARCHAR(1000) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending'
);

-- Prescriptions (master)
CREATE TABLE dbo.Prescriptions (
    PrescriptionId BIGINT IDENTITY(1,1) PRIMARY KEY,
    VisitId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Visits(VisitId) ON DELETE CASCADE,
    PrescribedByUserId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    PrescribedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Notes NVARCHAR(2000) NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Active'
);

-- Prescription items
CREATE TABLE dbo.PrescriptionItems (
    PrescriptionItemId BIGINT IDENTITY(1,1) PRIMARY KEY,
    PrescriptionId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Prescriptions(PrescriptionId) ON DELETE CASCADE,
    DrugId INT NOT NULL FOREIGN KEY REFERENCES dbo.Drugs(DrugId),
    Dose NVARCHAR(100) NULL,
    Frequency NVARCHAR(100) NULL,
    DurationDays INT NULL,
    Quantity INT NULL CHECK (Quantity >= 0)
);
CREATE INDEX IX_PrescriptionItems_Prescription ON dbo.PrescriptionItems(PrescriptionId);

/***************************************************************
8) Laboratory (LIS) - requests, samples, reports
***************************************************************/

CREATE TABLE dbo.LabRecords (
    LabRecordId BIGINT IDENTITY(1,1) PRIMARY KEY, -- Unique ID
    VisitId BIGINT NULL, -- Visit reference
    RequestedByUserId INT NULL, -- Doctor/nurse who requested
    RequestedForPatientId INT NOT NULL, -- Patient ID
    RequestedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(), -- When requested
    
    LabTestId INT NOT NULL, -- Test requested
    Status NVARCHAR(50) NOT NULL DEFAULT 'Requested', -- Overall status
    
    Result NVARCHAR(MAX) NULL, -- Test result
    PerformedAt DATETIME2 NULL, -- When test performed
    PerformedByUserId INT NULL, -- Lab technician
    
    SampleTrackingId NVARCHAR(200) NULL UNIQUE, -- Unique sample ID
    CollectedByUserId INT NULL, -- Who collected sample
    CollectedAt DATETIME2 NULL, -- When collected
    StorageLocation NVARCHAR(200) NULL, -- Where stored
    
    Notes NVARCHAR(1000) NULL -- Extra info
);
/***************************************************************
9) Pharmacy: inventory, dispensations, purchase orders
***************************************************************/

CREATE TABLE dbo.PharmacyInventory (
    InventoryId BIGINT IDENTITY(1,1) PRIMARY KEY,
    DrugId INT NOT NULL FOREIGN KEY REFERENCES dbo.Drugs(DrugId),
    BatchNumber NVARCHAR(100) NULL,
    QuantityOnHand INT NOT NULL CHECK (QuantityOnHand >= 0),
    ReorderLevel INT NOT NULL DEFAULT 0,
    ExpiryDate DATE NULL,
    WarehouseLocation NVARCHAR(200) NULL,
    CONSTRAINT UX_PharmacyInventory_Drug_Batch UNIQUE(DrugId, BatchNumber)
);
CREATE INDEX IX_PharmacyInventory_Drug ON dbo.PharmacyInventory(DrugId);

CREATE TABLE dbo.PurchaseOrders (
    PurchaseOrderId BIGINT IDENTITY(1,1) PRIMARY KEY,
    CreatedByUserId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Status NVARCHAR(50) NOT NULL DEFAULT 'Draft',
    Supplier NVARCHAR(200) NULL,
    TotalAmount DECIMAL(18,2) NOT NULL DEFAULT 0
);

CREATE TABLE dbo.PurchaseOrderItems (
    PurchaseOrderItemId BIGINT IDENTITY(1,1) PRIMARY KEY,
    PurchaseOrderId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.PurchaseOrders(PurchaseOrderId) ON DELETE CASCADE,
    DrugId INT NOT NULL FOREIGN KEY REFERENCES dbo.Drugs(DrugId),
    Quantity INT NOT NULL CHECK (Quantity > 0),
    UnitPrice DECIMAL(18,2) NOT NULL CHECK (UnitPrice >= 0)
);

-- Drug dispensation records (when pharmacy dispenses to patient)
CREATE TABLE dbo.DrugDispensations (
    DispensationId BIGINT IDENTITY(1,1) PRIMARY KEY, -- Unique transaction ID
    PrescriptionId BIGINT NULL, -- Links to doctor's prescription
    PatientId INT NOT NULL, -- Patient receiving the drugs
    InventoryId BIGINT NOT NULL, -- Drug from PharmacyInventory
    Quantity INT NOT NULL CHECK (Quantity > 0), -- Units dispensed
    UnitPrice DECIMAL(18,2) NOT NULL, -- Price per unit
    TotalPrice AS (Quantity * UnitPrice) PERSISTED, -- Auto-calculated total cost
    DispensedByUserId INT NOT NULL, -- Pharmacist/user who dispensed
    DispensedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), -- Date & time of dispensing
    Notes NVARCHAR(500) NULL, -- Additional info

    -- Foreign Keys
    CONSTRAINT FK_DrugDispensations_Prescription FOREIGN KEY (PrescriptionId)
        REFERENCES dbo.Prescriptions(PrescriptionId),
    CONSTRAINT FK_DrugDispensations_Patient FOREIGN KEY (PatientId)
        REFERENCES dbo.Patients(PatientId),
    CONSTRAINT FK_DrugDispensations_Inventory FOREIGN KEY (InventoryId)
        REFERENCES dbo.PharmacyInventory(InventoryId),
    CONSTRAINT FK_DrugDispensations_User FOREIGN KEY (DispensedByUserId)
        REFERENCES dbo.Users(UserId)
);
/***************************************************************
10) Ward & Bed management
***************************************************************/

CREATE TABLE dbo.Wards (
    WardId INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(150) NOT NULL,
    WardTypeId TINYINT NOT NULL FOREIGN KEY REFERENCES dbo.WardTypes(WardTypeId),
    Location NVARCHAR(200) NULL,
    UNIQUE (Name)
);

CREATE TABLE dbo.Beds (
    BedId INT IDENTITY(1,1) PRIMARY KEY,
    WardId INT NOT NULL FOREIGN KEY REFERENCES dbo.Wards(WardId),
    BedNumber NVARCHAR(50) NOT NULL,
    IsOccupied BIT NOT NULL DEFAULT 0,---1 and 0 active and inactive
    UNIQUE (WardId, BedNumber)
);
CREATE INDEX IX_Beds_Ward ON dbo.Beds(WardId);

CREATE TABLE dbo.Admissions (
    AdmissionId BIGINT IDENTITY(1,1) PRIMARY KEY,
    VisitId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Visits(VisitId) ON DELETE CASCADE,
    AdmittedByUserId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    AdmittedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    BedId INT NULL FOREIGN KEY REFERENCES dbo.Beds(BedId),
    DischargedAt DATETIME2 NULL,
    DischargedByUserId INT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    AdmissionNotes NVARCHAR(2000) NULL
);
CREATE INDEX IX_Admissions_Bed ON dbo.Admissions(BedId);

/***************************************************************
11) Ambulance & Dispatch
***************************************************************/

CREATE TABLE dbo.Ambulances (
    AmbulanceId INT IDENTITY(1,1) PRIMARY KEY,
    RegistrationNumber NVARCHAR(100) NOT NULL UNIQUE,
    ContactPhone NVARCHAR(30) NULL,
    StatusId TINYINT NOT NULL FOREIGN KEY REFERENCES dbo.AmbulanceStatus(AmbulanceStatusId),
    
);

CREATE TABLE dbo.DispatchLogs (
    DispatchId BIGINT IDENTITY(1,1) PRIMARY KEY,
    AmbulanceId INT NOT NULL FOREIGN KEY REFERENCES dbo.Ambulances(AmbulanceId),
    EmergencyCaseId BIGINT NULL, -- can link to emergencies table if created
    DispatchedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    DispatchedByUserId INT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    Destination NVARCHAR(300) NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Dispatched',
    Notes NVARCHAR(1000) NULL
);
CREATE INDEX IX_Dispatch_Ambulance_Status ON dbo.DispatchLogs(AmbulanceId, Status);

/***************************************************************
12) Billing & Finance
***************************************************************/

CREATE TABLE dbo.Invoices (
    InvoiceId BIGINT IDENTITY(1,1) PRIMARY KEY,
    VisitId BIGINT NULL FOREIGN KEY REFERENCES dbo.Visits(VisitId),
    PatientId INT NOT NULL FOREIGN KEY REFERENCES dbo.Patients(PatientId),
    CreatedByUserId INT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Total DECIMAL(18,2) NOT NULL DEFAULT 0,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Unpaid' -- Paid/PartiallyPaid/Canceled
);

CREATE TABLE dbo.InvoiceItems (
    InvoiceItemId BIGINT IDENTITY(1,1) PRIMARY KEY,
    InvoiceId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Invoices(InvoiceId) ON DELETE CASCADE,
    ServiceId INT NULL FOREIGN KEY REFERENCES dbo.Services(ServiceId),
    Description NVARCHAR(1000) NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    UnitPrice DECIMAL(18,2) NOT NULL CHECK (UnitPrice >= 0),
    LineTotal AS (Quantity * UnitPrice) PERSISTED
);
CREATE INDEX IX_Invoice_Patient ON dbo.Invoices(PatientId);

CREATE TABLE dbo.Payments (
    PaymentId BIGINT IDENTITY(1,1) PRIMARY KEY,
    InvoiceId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Invoices(InvoiceId),
    PaidAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Amount DECIMAL(18,2) NOT NULL CHECK (Amount > 0),
    PaymentMethodId TINYINT NOT NULL FOREIGN KEY REFERENCES dbo.PaymentMethods(PaymentMethodId),
    TransactionRef NVARCHAR(200) NULL
);

/***************************************************************
13) Insurance & Claims
***************************************************************/

CREATE TABLE dbo.InsurancePolicies (
    InsurancePolicyId INT IDENTITY(1,1) PRIMARY KEY,
    PolicyNumber NVARCHAR(200) NOT NULL UNIQUE,
    PatientId INT NOT NULL FOREIGN KEY REFERENCES dbo.Patients(PatientId),
    Provider NVARCHAR(200) NOT NULL,
    CoverageDetails NVARCHAR(2000) NULL,
    ValidFrom DATE NOT NULL,
    ValidTo DATE NULL
);

CREATE TABLE dbo.InsuranceClaims (
    ClaimId BIGINT IDENTITY(1,1) PRIMARY KEY,
    InvoiceId BIGINT NOT NULL FOREIGN KEY REFERENCES dbo.Invoices(InvoiceId),
    PolicyId INT NOT NULL FOREIGN KEY REFERENCES dbo.InsurancePolicies(InsurancePolicyId),
    SubmittedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Status NVARCHAR(50) NOT NULL DEFAULT 'Submitted',
    Amount DECIMAL(18,2) NOT NULL
);

/***************************************************************
14) Audit & Logs
***************************************************************/

CREATE TABLE dbo.AuditLogs (
    AuditLogId BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
    Event NVARCHAR(200) NOT NULL,
    EventData NVARCHAR(MAX) NULL,
    LoggedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE INDEX IX_AuditLogs_LoggedAt ON dbo.AuditLogs(LoggedAt);

/***************************************************************/


/*MUGISHA*/
create table finance.Bills(
    bill_id int primary key identity(1,1),
    patient_id int not null,
    admission_id int null,
    total_amount decimal(18,2) not null,
    status nvarchar(20) check(status in ('Paid','Pending','Partially Paid')),
    created_at datetime,
    foreign key (patient_id) references users.Patients(patient_id),
    foreign key (admission_id) references accommodation.Admissions(admission_id)
);

create table finance.Payments(
    payment_id int primary key identity(1,1),
    bill_id int not null,
    method nvarchar(20) check(method in ('Cash','Card','Insurance')),
    amount decimal(18,2) not null,
    reference nvarchar(100),
    paid_at datetime,
    staff_id int,
    foreign key (bill_id) references finance.Bills(bill_id),
    foreign key (staff_id) references users.Staff(staff_id)
);


-- Insurance Companies
CREATE TABLE finance.InsuranceCompanies (
    insurance_company_id INT PRIMARY KEY IDENTITY(1,1),
    name NVARCHAR(100) UNIQUE NOT NULL,
    contact_email NVARCHAR(100),
    contact_phone NVARCHAR(20),
    address NVARCHAR(200),
    status BIT DEFAULT 1 -- 1 = Active, 0 = Inactive
);

-- Insurance Policies
CREATE TABLE finance.InsurancePolicies (
    policy_id INT PRIMARY KEY IDENTITY(1,1),
    insurance_company_id INT NOT NULL,
    policy_name NVARCHAR(100) NOT NULL,
    coverage_details NVARCHAR(MAX),
    max_coverage_amount DECIMAL(18,2),
    status BIT DEFAULT 1,
    FOREIGN KEY (insurance_company_id) REFERENCES finance.InsuranceCompanies(insurance_company_id)
);

-- Patient Insurance
CREATE TABLE finance.PatientInsurance (
    patient_insurance_id INT PRIMARY KEY IDENTITY(1,1),
    patient_id INT NOT NULL,
    insurance_company_id INT NOT NULL,
    policy_id INT NOT NULL,
    policy_number NVARCHAR(100) NOT NULL UNIQUE,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    status NVARCHAR(20) CHECK(status IN ('Active','Expired','Pending')) DEFAULT 'Active',
    FOREIGN KEY (patient_id) REFERENCES users.Patients(patient_id),
    FOREIGN KEY (insurance_company_id) REFERENCES finance.InsuranceCompanies(insurance_company_id),
    FOREIGN KEY (policy_id) REFERENCES finance.InsurancePolicies(policy_id)
);

-- Insurance Claims
CREATE TABLE finance.InsuranceClaims (
    claim_id INT PRIMARY KEY IDENTITY(1,1),
    patient_id INT NOT NULL,
    bill_id INT NOT NULL,
    insurance_company_id INT NOT NULL,
    policy_id INT NOT NULL,
    claim_amount DECIMAL(18,2) NOT NULL,
    approved_amount DECIMAL(18,2) NULL,
    claim_status NVARCHAR(20) DEFAULT 'Pending' CHECK(claim_status IN ('Pending','Approved','Rejected')),
    claim_date DATETIME DEFAULT GETDATE(),
    processed_date DATETIME NULL,
    FOREIGN KEY (patient_id) REFERENCES users.Patients(patient_id),
    FOREIGN KEY (bill_id) REFERENCES finance.Bills(bill_id),
    FOREIGN KEY (insurance_company_id) REFERENCES finance.InsuranceCompanies(insurance_company_id),
    FOREIGN KEY (policy_id) REFERENCES finance.InsurancePolicies(policy_id)
);


create table inventory.Categories(
    category_id int primary key identity(1,1),
    name nvarchar(50) unique not null,
    description nvarchar(200)
);

CREATE TABLE inventory.Products (
    product_id INT PRIMARY KEY IDENTITY(1,1),
    category_id INT NOT NULL,
    name NVARCHAR(100) UNIQUE NOT NULL,
    description NVARCHAR(200),
    price DECIMAL(18,2) NOT NULL,
    status NVARCHAR(20) CHECK(status IN ('Available','Discontinued')),
    quantity INT NOT NULL CHECK(quantity >= 0), -- merged stock
    expiry_date DATE NULL,                     -- merged stock field
    created_at DATETIME DEFAULT GETDATE(),
    last_updated DATETIME DEFAULT GETDATE(),   -- merged from stock
    FOREIGN KEY (category_id) REFERENCES inventory.Categories(category_id)
);


--  Pharmacy sales + other hospital sales
create table inventory.Sales(
    sale_id int primary key identity(1,1),
    product_id int not null,
    bill_id int not null,
    quantity int not null,
    total_price decimal(18,2) not null,
    sale_date datetime,
    staff_id int,
    foreign key (product_id) references inventory.Products(product_id),
    foreign key (bill_id) references finance.Bills(bill_id),
    foreign key (staff_id) references users.Staff(staff_id)
);






